#!/bin/sh

# install home-manager
sudo nix-channel --add https://www.github.com/nix-community/home-manager/archive/release-23.11.tar.gz home-manager

# install doomhowl channel
sudo nix-channel --add https://www.github.com/bramtechs/nix-channel/archive/main.tar.gz doomhowl

sudo nix-channel --update
