services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
      - WEBUI_PORT=9000
      - TORRENTING_PORT=6881
    volumes:
      - /var/lib/qbittorrent/appdata:/config
      - /mnt/extra/downloads:/downloads
    ports:
      - 9000:9000
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
